services:
  - type: web
    name: cinema-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
    healthCheckPath: /health
    autoDeploy: true
